### PR TITLE
added proxy support for the scraper

### PR DESCRIPTION
**Pull request by ZakariaMQ**
when scrapping it is necessary to use a proxy so to avoid the limits, for that I took action to make this pull request
Thanks :)

### CODE REVIEW

**Comment by serkanozcan** [comment]
> when scrapping it is necessary to use a proxy so to avoid the limits, for that I took action to make this pull request Thanks :)

Hi please can you share an example how to avoid the limits? Thank you

**Comment by serkanozcan** [comment]
@trevorhobenshield please merge this commit

**Review by User-23173 — APPROVED** [review]

**Comment by trevorhobenshield** [comment]
Hey, @ZakariaMQ thanks for your code.

A quick clarification, Twitter tracks rate limits at the account-level, so proxies will not bypass rate limits.

With regards to the code, you're off to a great start, but there is a bit more work to do in order to implement this successfully. There are also a few limitations (e.g. httpx supports socks5 but not socks5h) that need to be addressed/resolved. I'll look into this further and get back to you, but will have to close this for now.

**Comment by ZakariaMQ** [comment]
Hey, @trevorhobenshield thanks for your reply.

what I meant by this pull request is to use multiple accounts each with its proxy 

anyway, I appreciate the great work you have done :)

**Pull request closed without merging**
